### PR TITLE
fix next scan disabled

### LINKED ISSUE #26: Fix the next scan button
Currently, the ⏩ icon that advances to the next scan is always grayed out. It should be enabled whenever the current scan is not the next scan.

### PR DESCRIPTION
**Pull request by venkatabhishek**
Fixes #26 
-  fixed next scan button
- removed big comment + improved some readability 

Notes:
- Not sure if this is necessary, but added logic to traverse through scans to find next available scan with images (i.e. ensures clicking next scan does not go to a scan with no images)

### CODE REVIEW

**Review by dchiquito — CHANGES_REQUESTED** [review]
I think it would be cleaner to set the `firstDatasetInNextSession` in the next iteration of the loop, rather than doing all that recursive lookup logic:
```
let lastImage = null;
for (image in images) {
  ...
  image.firstDatasetInNextSession = null;
  if (lastImage) {
    lastImage.firstDatasetInNextSession = image.id;
  }
}
```
I think it's fine to assume that scans have images in them. If they don't, some buttons don't work correctly, but users would still be able to open scans from the list instead.

**Comment by venkatabhishek** [comment]
If we don't have to worry about scans without images or experiments without scans, we don't need any recursive behavior. Based on this, I think it would still be more efficient to set the next scan in the current iteration of the loop. Specifically, if we had to do it in the next loop, it would require iterating over all images in the previous scan again to set `firstDatasetInNextSession` on each of them

**Review by dchiquito — APPROVED** [review]
Ah, I see. I parsed it as a chain of images, but actually each image tracks the next scan for some reason? Smells like something that shouldn't necessarily be tracked at the image level, but that sounds like a bigger refactor.

LGTM

**Comment by dzenanz** [comment]
> each image tracks the next scan

Since we need this for the "next" button, it is computed once instead of being recomputed many times. I think Scott said it was one of performance optimizations he did early on.

**Comment by venkatabhishek** [comment]
Yes, I agree that a lot of refactoring needs to be done. Much of the data is being re-used/duplicated throughout. For example, instead of passing the next scan to each image, we should just add it to the current scan once, and use that to render the next/previous scan button. Does this warrant another PR or should I add it to this one?

**Pull request merged**
